BLUE_EXAMPLES: |
  The Situation: 
  The Game map is a 8x8 grid.
  Available Mineral Fields: 2
  - Mineral Fields(0, 0) resource: 20
  - Mineral Fields(7, 7) resource: 20
  You are in the blue side.

  Red's Resource: 5
  Red's Units:
  base: 1
  - (6, 5), action: noop
  barrack: 0
  worker: 1
  - (6, 6), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Blue's Resource: 5
  Blue's Units:
  base: 1
  - (1, 2), action: noop
  barrack: 0
  worker: 1
  - (1, 1), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Gaming Plan:
  START OF TASK
  [Harvest Mineral](0, 0),
  [Produce Unit]('worker', 'east'),
  [Harvest Mineral](0, 0),
  [Produce Unit]('worker', 'south'),
  [Produce Unit]('worker', 'east'),
  [Produce Unit]('worker', 'south'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Build Building]('barrack', (0, 3)),
  [Produce Unit]('ranged', 'east'),
  [Produce Unit]('ranged', 'south'),
  [Attack Enemy]('ranged', 'worker'),
  [Attack Enemy]('ranged', 'worker'),
  [Attack Enemy]('ranged', 'base'),
  [Attack Enemy]('ranged', 'base'),
  END OF TASK

  The Situation: 
  The Game map is a 8x8 grid.
  Available Mineral Fields: 2
  - Mineral Fields(0, 0) resource: 10
  - Mineral Fields(7, 7) resource: 17
  You are in the blue side.

  Red's Resource: 2
  Red's Units:
  base: 1
  - (6, 5), action: produce
  barrack: 0
  worker: 5
  - (2, 5), action: noop
  - (5, 2), action: noop
  - (5, 5), action: noop
  - (7, 2), action: noop
  - (7, 3), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Blue's Resource: 8
  Blue's Units:
  base: 1
  - (1, 2), action: produce
  barrack: 0
  worker: 6
  - (0, 1), action: noop
  - (1, 0), action: noop
  - (1, 3), action: produce
  - (1, 4), action: noop
  - (2, 1), action: noop
  - (2, 2), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Gaming Plan:
  START OF TASK
  [Harvest Mineral](0, 0),
  [Harvest Mineral](0, 0),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Build Building]('barrack', (0, 4)),
  [Produce Unit]('worker', 'east'),
  [Produce Unit]('worker', 'south'),
  [Produce Unit]('worker', 'east'),
  [Produce Unit]('worker', 'south'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Produce Unit]('ranged', 'east'),
  [Produce Unit]('ranged', 'south'),
  [Attack Enemy]('ranged', 'base'),
  [Attack Enemy]('ranged', 'base'),
  END OF TASK

RED_EXAMPLES: |
  The Situation: 
  The Game map is a 8x8 grid.
  Available Mineral Fields: 2
  - Mineral Fields(0, 0) resource: 20
  - Mineral Fields(7, 7) resource: 20
  You are in the red side.

  Red's Resource: 5
  Red's Units:
  base: 1
  - (6, 5), action: noop
  barrack: 0
  worker: 1
  - (6, 6), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Blue's Resource: 5
  Blue's Units:
  base: 1
  - (1, 2), action: noop
  barrack: 0
  worker: 1
  - (1, 1), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Gaming Plan:
  START OF TASK
  [Harvest Mineral](7, 7),
  [Produce Unit]('worker', 'east'),
  [Harvest Mineral](7, 7),
  [Produce Unit]('worker', 'south'),
  [Produce Unit]('worker', 'east'),
  [Produce Unit]('worker', 'south'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Build Building]('barrack', (7, 3)),
  [Produce Unit]('ranged', 'east'),
  [Produce Unit]('ranged', 'south'),
  [Attack Enemy]('ranged', 'worker'),
  [Attack Enemy]('ranged', 'worker'),
  [Attack Enemy]('ranged', 'base'),
  [Attack Enemy]('ranged', 'base'),
  END OF TASK

  The Situation: 
  The Game map is a 8x8 grid.
  Available Mineral Fields: 2
  - Mineral Fields(0, 0) resource: 10
  - Mineral Fields(7, 7) resource: 17
  You are in the blue side.

  Red's Resource: 2
  Red's Units:
  base: 1
  - (6, 5), action: produce
  barrack: 0
  worker: 5
  - (2, 5), action: noop
  - (5, 2), action: noop
  - (5, 5), action: noop
  - (7, 2), action: noop
  - (7, 3), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Blue's Resource: 8
  Blue's Units:
  base: 1
  - (1, 2), action: produce
  barrack: 0
  worker: 6
  - (0, 1), action: noop
  - (1, 0), action: noop
  - (1, 3), action: produce
  - (1, 4), action: noop
  - (2, 1), action: noop
  - (2, 2), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Gaming Plan:
  START OF TASK
  [Harvest Mineral](0, 0),
  [Harvest Mineral](0, 0),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Build Building]('barrack', (7, 4)),
  [Produce Unit]('worker', 'east'),
  [Produce Unit]('worker', 'south'),
  [Produce Unit]('worker', 'east'),
  [Produce Unit]('worker', 'south'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Attack Enemy]('worker', 'worker'),
  [Produce Unit]('ranged', 'east'),
  [Produce Unit]('ranged', 'south'),
  [Attack Enemy]('ranged', 'base'),
  [Attack Enemy]('ranged', 'base'),
  END OF TASK

TIPS: |
  - Economy is the top priority. Two workers harvest mineral will be more efficient.
  - Workers offer a better cost-effectiveness, so produce them in large quantities.
  - Offense is the best defense. Workers can also attack enemies. Try to let the worker attack more often.
  - If an enemy approaches the base, prioritize protecting the base and use all available forces to eliminate them. 
  - Build barracks only when you have surplus resources.
  - Use more ranged units, which can help you win the game more easily.
