EXAMPLES: |
  - Two workers will be more efficient in harvesting, but do not exceed two.
  - First, determine the difference between the number of our workers and the number of enemy workers in the current situation. If our number is less than the enemy, please create more workers to make up for the difference.
  - Workers offer a better cost-effectiveness, so produce them in large quantities
  - Offense is the best defense. Workers can also attack enemies. Try to let the worker attack more often
  - The enemy will probably continue to create worker invasions in the next period of time, so we need a large number of [attack enemies] (workers, workers).
  - Keep producing workers to attack the enemy. We can defeat the enemy with the power of workers alone.
  - If there are no resources left to harvest in the current situation, let's attack with all our workers.
  - As long as our side have resources, don't stop producing workers. Don't stop the invasion.
  - Workers are the most important unit in the game. Produce them as much as possible.
  - Judge the current situation. If there are enemy units approaching the base, the most important thing is to destroy them.
  - Attack the enemy base to prevent them from returning resources to the base.
  - If the enemy has a barracks, attack the local barracks first to prevent them from producing high-level soldiers.
  - If your resources are less than 8, please do not build a barracks.
  - When your resources are greater than 8, you only need one worker to harvest resources and start building barracks, but don't forget to continue making workers and launching attacks.
