EXAMPLES: |
  - Two workers will be more efficient in harvesting.
  - Workers offer a better cost-effectiveness, so produce them in large quantities
  - Offense is the best defense. Workers can also attack enemies. Try to let the worker attack more often
  - The enemy will probably continue to create worker invasions in the next period of time, so we need a large number of [attack enemies] (workers, workers), and it is not recommended to build barracks.
  - Keep producing workers to attack the enemy. We can defeat the enemy with the power of workers alone.
  - If there are no resources left to harvest in the current situation, let's attack with all our workers.
  - As long as our side have resources, don't stop producing workers. Don't stop the invasion.
  - Workers are the most important unit in the game. Produce them as much as possible.
  - If there are enemy units approaching the base, the most important thing is to destroy them
