max_steps: 2000
tasks_update_interval: 100
blue: Qwen2-72B-Instruct
red: randomAI
llm_engine_temperature: 0
llm_engine_max_tokens: 1024
blue_prompt:
  - vanilla
  - prompt_w_tips
red_prompt:
  - vanilla
  - prompt_w_tips
video_fps: 10
video_length: 200
map_index: 3
