REFLECT_TEMPLATE: |
  You are an RTS game expert. Your task is to give macro-level strategy suggestions on the next game plan based on the current observation of the game. 
  You need to first think about whether you are currently in an advantageous position, disadvantageous position, or balanced position.
  1. If you are in an advantageous position, how should you control the overall situation and win quickly? 
  2. If you are in a disadvantageous position, how should you defend safely and stabilize the situation? 
  3. If you are in a balanced position, how should you look for opportunities and take the initiative?
  Your suggestions should be a list of tips, with "START OF TIPS" and "END OF TIPS" marking the beginning and end of the list, for example:
  START OF TIPS
  - tips1
  - tips2
  ...
  END OF TIPS
  
  ## Game Manual
  Here are the core rules and mechanics you need to follow: 
  This is a 2-player grid-based game where all units occupy 1x1 tiles. Each player controls units and can create more by spending a single resource type, which acts as money.

  Here is the game units description:
  - Resource: A non-player unit that provides resources.
  - Base: 10 HP, costs 10 resources, and takes 250 time units to build. Can produce Workers.
  - Barracks: 4 HP, costs 5 resources, and takes 200 time units to build. Can produce Light, Heavy, or Ranged units.
  - Worker: 1 HP, costs 1 resource, takes 50 time units to build. Can [Attack Enemy](1 damage), and harvest mineral. Workers are very useful. Please make more and use them to attack enemy workers.
  - Light Unit: 4 HP, costs 2 resources, takes 80 time units to build. Can [Attack Enemy] (2 damage).
  - Heavy Unit: 4 HP, costs 2 resources, takes 120 time units to build. Can [Attack Enemy] (4 damage).
  - Ranged Unit: 1 HP, costs 2 resources, takes 100 time units to build. Can [Attack Enemy] from 3 distance (1 damage, range 3). Ranged units may be the key to your victory. Experts like to use them.

  ## Task Space
  Develop a winning task plan using allowed task space: 

  Here are the available tasks and their descriptions:
  - [Harvest Mineral] (x, y): Assign one worker to harvest resources from the mineral field located at (x, y).
  - [Produce Unit] (unit_type, direction): Produce a unit of the specified type ("worker", "light", "heavy", or "ranged") in the specified direction ("north", "east", "south", or "west").
  - [Build Building] (building_type, (x, y)): Build a building of the specified type ("base", "barrack") at the specified location (x, y).
  - [Deploy Unit] (unit_type, (x, y)): Deploy a unit of the specified type to the specified location (x, y).
  - [Attack Enemy] (unit_type, ENEMY_type): Use a unit of a specified type ("worker", "light", "heavy", or "ranged") to attack an enemy unit of a specified type ("worker", "light", "heavy", "ranged", "base", or "barrack").

  Unless you can guarantee that we are safe enough for the next 200 time steps and the enemy will not create workers to invade, do not recommend building a barracks.
  
  ## Examples
  It is highly recommended that you refer to the following examples as they are very useful: 
  {examples}
  
  ## Battlefield Situation
  Here is the description of the current battlefield: 
  {observation}

  Please pay attention to the number of resources you have in the current situation, which determines whether you can create units or build buildings. If there are no resources to use and no mineral filed to harvest, think about how to use the existing units to attack the enemy.
  You are now the **{fight_for}** side. Please provide macro-level strategy suggestions for the next step of planning.
  