EXAMPLES: |
  The Situation: 
  The Game map is a 8x8 grid.
  Available Mineral Fields: 2
  - Mineral Fields(0, 0) resource: 10
  - Mineral Fields(7, 7) resource: 17
  You are in the **blue** side.

  Red's Resource: 6
  Red's Units:
  base: 1
  - (6, 5), action: produce
  barrack: 0
  worker: 5
  - (2, 5), action: noop
  - (5, 2), action: noop
  - (5, 5), action: noop
  - (7, 2), action: noop
  - (7, 3), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Blue's Resource: 5
  Blue's Units:
  base: 1
  - (1, 2), action: produce
  barrack: 0
  worker: 6
  - (0, 1), action: noop
  - (1, 0), action: noop
  - (1, 3), action: produce
  - (1, 4), action: noop
  - (2, 1), action: noop
  - (2, 2), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Gaming Plan:
  START OF TASK
  [Harvest Mineral](0, 0)
  [Harvest Mineral](0, 0)
  [Produce Unit](worker, east)
  [Produce Unit](worker, south)
  [Produce Unit](worker, east)
  [Produce Unit](worker, south)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, barrack)
  [Attack Enemy](worker, base)
  END OF TASK

  The Situation: 
  The Game map is a 8x8 grid.
  Available Mineral Fields: 2
  - Mineral Fields(0, 0) resource: 15
  - Mineral Fields(7, 7) resource: 16
  You are in the **red** side.

  Red's Resource: 10
  Red's Units:
  base: 1
  - (6, 5), action: noop
  barrack: 0
  worker: 4
  - (2, 2), action: noop
  - (4, 4), action: noop
  - (5, 5), action: noop
  - (7, 5), action: noop
  light: 0
  heavy: 0
  ranged: 0
  
  Blue's Resource: 6
  Blue's Units:
  base: 1
  - (1, 2), action: noop
  barrack: 1
  - (0, 4) action: produce
  worker: 4
  - (0, 1), action: harvest
  - (0, 3), action: noop
  - (1, 1), action: noop
  - (1, 3), action: noop
  light: 0
  heavy: 0
  ranged: 0

  Gaming Plan:
  START OF TASK
  [Harvest Mineral](7, 7)
  [Build Building](barrack, (7, 4))
  [Produce Unit](worker, east)
  [Produce Unit](worker, south)
  [Produce Unit](worker, east)
  [Produce Unit](worker, south)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, worker)
  [Attack Enemy](worker, barrack)
  [Attack Enemy](worker, base)
  [Attack Enemy](worker, base)
  END OF TASK

TIPS: |
  - Two workers will be more efficient in harvesting, but do not exceed two.
  - Workers offer a better cost-effectiveness, so produce them in large quantities, i.e. [Produce Unit] x4.
  - Attack the enemy base to prevent them from returning resources to the base.
  - If the enemy has a barracks, attack the barracks first to prevent them from producing high-level soldiers.
  - The enemy will probably continue to create worker invasions in the next period of time, so we need a large number of [Attack Enemy] (workers, workers).
  - If there are no resources left to harvest in the current situation, let's attack with all our workers.
  - As long as our side have resources, don't stop producing workers. Don't stop the invasion.
  - If your resources are less than 8, please do not build a barracks.
  - When your resources are greater than 8, you only need one worker to harvest resources and building barracks near to base first (top priority), but don't forget to continue making workers and launching attacks.
  - When a have a barrack, produce a ranged first.
